import type { NextPage } from 'next'
import Head from 'next/head'
import {home} from '../styles/style'
import {Nav, Card, Loading, Skill} from './components/basic';
import {useState, useEffect} from 'react';
import {motion} from 'framer-motion';
import {Cursor, useTypewriter } from 'react-simple-typewriter'


const Home: NextPage = () => {
  const [isDisplay, setIsDisplay] = useState(false);
  const [text, count] = useTypewriter({
		words:[
			"Hi, my name is Saleh", 
			"You can call me as Fate", 
			"I like playing rpg games!", 
		],
		loop:true, 
		delaySpeed:2000,
	});
	const [runCount, setRunCount] = useState(0);
  useEffect(() => {
  if (runCount >= 1) {
    return;
  }

  const interval = setInterval(() => {
    setIsDisplay(current => !current);
    setRunCount(runCount + 1);
  }, 1000);

  return () => clearInterval(interval);
});

  return (
    <div className={home.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<Loading display={isDisplay? 'none':'flex'} />
			<main className={home.main} style={{display: isDisplay? 'flex':'none'}}>
				<Nav/>
				<div className={home.hero}>
					<div className={home.ring}></div>
					<span id={home.hero}>
						<img/>
						<p>Frontend Developer</p>
						<h3>
							<span>{text}</span>
							<Cursor cursorColor="red"/>
						</h3>
						<div className={home.link}>
							<a>About</a>
							<a>Skills</a>
							<a>Projects</a>
							<a>Contact</a>
						</div>
					</span>
				</div>
				<div className={home.point}><h3>About Me</h3></div>
				<motion.div initial={{
			x: -100,
			opacity: 0, 
					}}
					whileInView={{
			x: 0, 
			opacity: 1,
					}}
					transition={{duration: 1}}
					viewport={{once:true}}
					>	
				<div className={home.about}>
					<img/>
					<span>
						<h2>Here is a little about me</h2>
						<p>Hey, I am Abu Saleh also known as Fate. I am a junior frontend developer from Bangladesh. I mainly like building websites, web designs, any kinds of graphic designs. I am available on Youtube, Facebook, Discord and of course LinkedIn. I started my coding journey at 2020 after learning everything related to graphic design. At first I learned html, css and java script then slowly react and later next js. Currently I am working as a Freelancer on Fiverr. </p>
						<a>Read more</a>
					</span>
				</div>
				</motion.div>
				<div className={home.point}><h3>Projects</h3></div>
				<Card/>
				<div className={home.point}><h3>Skills</h3></div>
				<Skill/>
			</main>
    </div>
  )
}

export default Home
