import type { NextPage } from 'next'
import Head from 'next/head'
import {home} from '../styles/style'
import {Nav, Card, Loading, Skill} from './components/basic';
import {meryl, alyss, claudia, zhongli, zilong, seele, fanny, gusion} from '../public/images/image';
import {useState, useEffect} from 'react';
import {motion} from 'framer-motion';
import {Cursor, useTypewriter } from 'react-simple-typewriter'
import {Swiper, SwiperSlide} from 'swiper/react';
import {EffectFade, A11y, Autoplay} from 'swiper';
import 'swiper/css';
import "swiper/css/effect-fade";


const Home: NextPage = () => {
  const [isDisplay, setIsDisplay] = useState(false);
  const [text, count] = useTypewriter({
		words:[
			"Hi, my name is Saleh", 
			"You can call me as Fate", 
			"I like playing rpg games!", 
		],
		loop:true, 
		delaySpeed:2000,
	});
	const [runCount, setRunCount] = useState(0);
  useEffect(() => {
  if (runCount >= 1) {
    return;
  }

  const interval = setInterval(() => {
    setIsDisplay(current => !current);
    setRunCount(runCount + 1);
  }, 1000);

  return () => clearInterval(interval);
});

  return (
    <div className={home.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<Loading display={isDisplay? 'none':'flex'} />
			<main className={home.main} style={{display: isDisplay? 'flex':'none'}}>
				<Nav/>
				<div className={home.hero}>
					<div className={home.ring}></div>
					<span id={home.hero}>
						<img src={zhongli} />
						<p>Frontend Developer</p>
						<h3>
							<span>{text}</span>
							<Cursor cursorColor="red"/>
						</h3>
						<div className={home.link}>
							<a href="#about"><p>About</p></a>
							<a href="#skill"><p>Skills</p></a>
							<a href="#card"><p>Projects</p></a>
							<a><p>Contact</p></a>
						</div>
					</span>
				</div>
				<div className={home.point}><h3>About Me</h3></div>
				<motion.div initial={{
			x: -100,
			opacity: 0, 
					}}
					whileInView={{
			x: 0, 
			opacity: 1,
					}}
					transition={{duration: 1}}
					viewport={{once:true}}
					>	
				<div className={home.about} id="about">
						<Swiper
							slidesPerView={1}
							effect={"fade"}
							modules={[EffectFade, Autoplay]}
							loop={true}
							className={home.image}
							autoplay={{
								delay:2500,           disableOnInteraction: false,
 }}
							centeredSlides={true}
							>
							<SwiperSlide><img src={meryl} style={{objectPosition: "40%"}} /></SwiperSlide>
							<SwiperSlide><img src={zilong} style={{objectPosition: "30%"}}/></SwiperSlide>
							<SwiperSlide><img src={alyss} style={{objectPosition: "70%"}} /></SwiperSlide>
							<SwiperSlide><img src={seele} /></SwiperSlide>
							<SwiperSlide><img src={zhongli} /></SwiperSlide>
							<SwiperSlide><img src={claudia} style={{objectPosition: "60%"}} /></SwiperSlide>
							<SwiperSlide><img src={fanny} style={{objectPosition: "60%"}}/></SwiperSlide>
							<SwiperSlide><img src={gusion} /></SwiperSlide>
						</Swiper>
					<span>
						<h2>Here is a little about me</h2>
						<p>Hey, I am Abu Saleh also known as Fate. I am a frontend developer from Bangladesh. I mainly like building websites, web designs, any kinds of graphic designs. I am available on Youtube, Facebook, Discord and of course LinkedIn. I started my coding journey at 2020 after learning everything related to graphic design. Currently I am working as a Freelancer on Fiverr. </p>
						<a>Read more</a>
					</span>
				</div>
				</motion.div>
				<div className={home.point} id="card"><h3>Projects</h3></div>
				<Card/>
				<div className={home.point} id="skill"><h3>Skills</h3></div>
				<Skill/>
			</main>
    </div>
  )
}

export default Home
